name: 'master_build'
on:
  push:
    branches: [ master ]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build & Test Microservice
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./mvnw clean verify -U -B -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST
      - name: Verify Success of Build
        run: ls -la target
      - name: Docker Build Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.AWS_IMAGE }}
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Fill in the new image ID in the Amazon ECS task definition
      #   id: task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
      #     container-name: ${{ secrets.CONTAINER_NAME }}
      #     image: ${{ steps.build-image.outputs.image }}
      #   continue-on-error: true     
      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: ${{ secrets.ECS_NAME }}
      #     cluster: ${{ secrets.ECS_NAME }}
      #     wait-for-service-stability: true
      #   continue-on-error: true     
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jars
          path: |
            target/openwms-common-service*.jar
        continue-on-error: true     

      